name: HackKernel
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: najahi/oven:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Compile Kernel
        run: |
          wget https://raw.githubusercontent.com/Kry9toN/Scripts/master/kernel/CI/vince/semaphore49
          bash semaphore49
