version: v1.0
name: HackKernel
agent:
  machine:
    type: e1-standard-2
  containers:
  - name: Masak
    image: najahi/oven:latest
blocks:
  - name: "Build"
    task:
      jobs:
      - name: Compile Kernel
        commands:
          - checkout
          - wget https://raw.githubusercontent.com/Kry9toN/Scripts/master/vince/semaphore49
          - bash semaphore49
