name: HackKernel
on:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup
        run: |
           apt install unzip -y
           wget https://github.com/kdrag0n/proton-clang/archive/refs/tags/20210522.zip
           unzip 20210522.zip
           ls
           pwd
#          apt install bc bison build-essential ccache curl flex g++-multilib gcc-multilib git git-lfs gnupg gperf imagemagick lib32ncurses5-dev lib32readline-dev lib32z1-dev libelf-dev liblz4-tool libncurses5 libncurses5-dev libsdl1.2-dev libssl-dev libxml2 libxml2-utils lzop pngcrush rsync schedtool squashfs-tools xsltproc zip zlib1g-dev adb fastboot -y
#          export CC=clang
#          export CLANG_TRIPLE=aarch64-linux-gnu-
#          export CROSS_COMPILE=aarch64-linux-gnu-
#          export CROSS_COMPILE_ARM32=arm-linux-gnueabi-
#          export ARCH=arm64
#          export PATH=$PATH:~/build_kernel/builder/proton-clang-20210522/bin/
#      - name: Checkout
#        uses: actions/checkout@v2
#      - name: Compile Kernel
#        run: |
#          wget https://raw.githubusercontent.com/Kry9toN/Scripts/master/kernel/CI/vince/semaphore49
#          bash semaphore49
